language: perl6
perl6:
    - latest

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - rakudobrew build-panda
    - panda install LibraryMake

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script: panda-build && prove -e perl6 t

